[phases.setup]
nixPkgs = ['python39', 'postgresql']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT --timeout 600 --workers 1 --threads 2 --worker-class sync'
