[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 600 --workers 1 --threads 2"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
